name: carp_mobile_sensing_app
description: The CARP Mobile Sensing App
version: 0.20.0
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/apps/carp_mobile_sensing_app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0
  
  #carp_core: ^0.20.0      # the core CARP domain model
  #carp_mobile_sensing: ^0.20.0
  #carp_connectivity_package: ^0.11.0
  #carp_context_package: ^0.11.0
  #carp_audio_package: ^0.11.0
  #carp_communication_package: ^0.11.0
  #carp_apps_package: ^0.11.0
  #carp_survey_package: ^0.11.0
  #carp_esense_package: ^0.11.0
  #carp_backend: ^0.11.0
  #carp_health_package: ^1.2.0
  #carp_firebase_backend: ^0.11.0

# Overriding carp libraries to use the local copy
dependency_overrides:
  carp_core:
    path: ../../carp_core/
  carp_mobile_sensing:
    path: ../../carp_mobile_sensing/
  carp_context_package:
    path: ../../packages/carp_context_package/
#  carp_connectivity_package:
#    path: ../../packages/carp_connectivity_package/
  carp_audio_package:
    path: ../../packages/carp_audio_package/
  carp_esense_package:
    path: ../../packages/carp_esense_package/
  carp_backend:
    path: ../../backends/carp_backend/
  carp_webservices:
    path: ../../backends/carp_webservices/
  research_package:
    path: ../../../../research.package/


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# Is used to change the default app launch icons on iOS and Android.
# To install:
#  1. import the 'flutter_launcher_icons' package above
#  2. add the 'flutter_icons:' section below
#  3. run 'flutter pub get'
#  3. run 'flutter pub pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: "assets/cachet_logo.png"


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/study.png
    - assets/cachet_logo.png
    - assets/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
