name: carp_mobile_sensing
description: Mobile Sensing Framework for Flutter. A software framework for collecting sensor data from the phone and attached wearable devices via probes. Can be extended.
version: 0.21.4
homepage: https://github.com/cph-cachet/carp.sensing-flutter
author:  CACHET Team <cph.cachet@gmail.com>

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  carp_core: ^0.21.4      # the core CARP domain model

  # utility plugins
  system_info: ^0.1.0
  uuid: ^2.0.0
  async: ^2.4.0
  device_info: '>=0.4.2 <2.0.0'
  json_annotation: ^3.0.0
  path_provider: ^1.2.0
  archive: ^2.0.4
  permission_handler: ^5.0.0
  shared_preferences: '>=0.5.7 <2.0.0'
  package_info: '>=0.4.0 <2.0.0'
  meta: ^1.1.8
  permission_handler_platform_interface: ^2.0.1
  cron: ^0.2.3            # For scheduling / triggering cron jobs

  # probe-dependent plugins
  sensors: '>=0.4.2 <2.0.0'
  battery: '>=0.3.0 <2.0.0'
  stats: ^1.0.0           # For calculating statistics, ex LightProbe

  # the CACHET plugins
  pedometer: ^2.1.0       # Get the step count from local OS
  light: ^1.0.1           # Light sensor over platform channel
  device_apps: ^1.0.8     # Device installed apps over platform channel
  screen_state: ^1.0.0    # Screen LOCK/ON/OFF

# Overriding carp core libraries to use the local copy
# Remove this before release of package
#dependency_overrides:
#  carp_core:
#    path: ../carp_core/


dev_dependencies:
  pedantic: ^1.9.0        # For pedantic Dart linter
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0   # For building json serialization
  json_serializable: ^3.0.0
  test:

# The following section is specific to Flutter.
flutter:

