name: carp_firebase_backend_example
description: Examples of how to use the plugin to upload data to Google Firebase.
version: 0.0.2
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/carp_firebase_backend
publish_to: none

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  carp_core:
#    path: ../../../carp_core
#  carp_mobile_sensing:
#    path: ../../../carp_mobile_sensing
  carp_firebase_backend:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:       # used to build JSON serialization .g files
  json_serializable: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

