name: carp_webservices
description: Flutter API for accessing the CARP web services - authentication, file management, data points, and app-specific collections of documents.
version: 0.21.4
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/backends/carp_webservices

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carp_mobile_sensing: ^0.21.4  # the CAMS domain model

  http: ^0.12.0
  http_parser: ^3.1.0
  uuid: ^2.0.0
  json_annotation: ^3.0.0
  retry: ^3.0.0
  meta: ^1.2.0
  form_field_validator: ^1.0.1
  rflutter_alert: ^1.1.0


# Overriding carp libraries to use the local copy
# Remove this before release of package
dependency_overrides:
#  carp_core:
#    path: ../../carp_core/
#  carp_mobile_sensing:
#    path: ../../carp_mobile_sensing/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.0.0
  test:

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - asset/images/

