# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
linter:
  rules:
    avoid_shadowing_type_parameters: true
    await_only_futures: true
    camel_case_types: true
    omit_local_variable_types: false
    #constant_identifier_names: false
    #avoid_classes_with_only_static_members: false
    annotate_overrides: false

analyzer:
  exclude:
    - lib/data_managers/*.g.dart
    - lib/domain/*.g.dart
    - lib/sampling_packages/device/*.g.dart
    - lib/sampling_packages/sensors/*.g.dart
    #- test/*.dart
    #- example/**

